[package]
name = "pretty_assertions_macro"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-lang-macro = "0.1.0"
cairo-lang-parser = "2.7.0"
cairo-lang-syntax = "2.7.0"