[package]
name = "pretty_assertions_macro"
version = "0.1.0"
edition = "2024_07"
authors = ["Michael Zaikin <michael.zaikin@starkware.co>"]
license = "MIT OR Apache-2.0"
description = "Drop-in replacement for the assert_eq! inline macro, which works outside of tests as well!"
repository = "https://github.com/m-kus/cairo-pretty-assertions"
homepage = "https://github.com/m-kus/cairo-pretty-assertions"
readme = "README.md"

[cairo-plugin]