[package]
name = "pretty_assertions"
version = "0.1.0"
edition = "2024_07"
authors = ["Michael Zaikin <michael.zaikin@starkware.co>"]
license = "MIT OR Apache-2.0"
description = "Pretty assertions for equality checks"
repository = "https://github.com/m-kus/cairo-pretty-assertions"
homepage = "https://github.com/m-kus/cairo-pretty-assertions"
readme = "README.md"

[dependencies]
diff = { path = "../diff" }
pretty_assertions_macro = { path = "../pretty_assertions_macro" }

[dev-dependencies]
cairo_test.workspace = true