[package]
name = "pretty_assertions_examples"
version = "0.1.0"
edition = "2024_07"

[dependencies]
pretty_assertions = { path = "../packages/pretty_assertions" }

[dev-dependencies]
cairo_test = "2.8.0"